
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckshblaukuwoqkfzvvdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrc2hibGF1a3V3b3FrZnp2dmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjM2MDYsImV4cCI6MjA1NzE5OTYwNn0.oDX8saJzAh2yE79z5iJEHCbwINlv-yX8zoYjWu0k2fM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
